import { buildTimingAnalysis, formatTimingEvidence } from '../../lib/timing/timingFramework.js';

const monthLabel = (row) => `${row.label} · ${row.score}/100`;

export function renderLaunchTimingModule(container, seasonalityRows, competitorRows) {
  const analysis = buildTimingAnalysis(seasonalityRows, competitorRows);
  const evidence = formatTimingEvidence(analysis);
  container.innerHTML = `<section class="timing-module" aria-labelledby="timing-module-title">
    <header class="timing-header"><div><p class="timing-eyebrow">Independent module / Exhibits 3 & 12</p><h2 id="timing-module-title">When should LUMEN launch in Germany?</h2><p>A transparent timing screen combining observed demand seasonality, temperature and competitor activity. It does not estimate price, channels, market priority or positioning.</p></div></header>
    <div class="timing-recommendation"><p class="timing-eyebrow">Preferred launch period</p><h3>${monthLabel(analysis.preferred)}</h3><p>${evidence.preferred}</p><span>Alternative: ${monthLabel(analysis.alternative)}</span></div>
    <div class="timing-grid"><section class="timing-card"><h3>Monthly timing score</h3><p class="timing-note">Observed data is shown in the table; the score is a transparent prioritisation aid. Prices are average competitor shelf prices.</p><table><thead><tr><th>Month</th><th>Demand</th><th>Temp.</th><th>Avg shelf €</th><th>Promos</th><th>Interaction −</th><th>Score</th></tr></thead><tbody>${analysis.ranked.map((row) => `<tr class="${row.month === analysis.preferred.month ? 'is-preferred' : ''}"><td>${row.label}</td><td>${row.demandIndex}</td><td>${row.temperatureC}°C</td><td>${row.averageShelfPrice === null ? '—' : row.averageShelfPrice.toFixed(2)}</td><td>${row.promotions.length ? row.promotions.length : '—'}</td><td>${row.demandCompetitionPenalty ? `−${row.demandCompetitionPenalty}` : '—'}</td><td><strong>${row.score}</strong></td></tr>`).join('')}</tbody></table></section>
      <section class="timing-card"><h3>Score framework</h3><div class="timing-bars"><div><span>Demand seasonality</span><b>45%</b></div><div><span>Temperature fit</span><b>20%</b></div><div><span>Price stability</span><b>20%</b></div><div><span>Promotion avoidance</span><b>15%</b></div><div><span>Demand × promotion interaction</span><b>up to −12</b></div></div><p class="timing-note">Price stability compares list and shelf prices. Promotion avoidance penalises active discounts; the interaction makes that penalty larger in high-demand months. This is a decision aid, not a sales forecast.</p></section></div>
    <section class="timing-evidence"><h3>Evidence and limits</h3><p><b>Seasonality:</b> ${evidence.seasonality}</p><p><b>Competition:</b> ${evidence.competition}</p><p><b>Unusual observations:</b> ${evidence.unusual}</p><p><b>Data quality:</b> ${analysis.dataQuality.missingSeasonalityValues + analysis.dataQuality.missingCompetitorValues === 0 ? 'No missing values detected in the required fields.' : 'Missing values are retained as neutral scores and disclosed.'}</p><p><b>Assumptions:</b> ${evidence.assumptions}</p><p><b>Confidence / uncertainty:</b> ${evidence.uncertainty}</p></section>
  </section>`;
  return { analysis, evidence };
}
