'use strict';
const assert = require('node:assert/strict'); const fs = require('node:fs'); const path = require('node:path');
const { parseCsv, normaliseInputs } = require('./data'); const { analysePricing } = require('./analysis');
const read = (name) => parseCsv(fs.readFileSync(path.join(__dirname, '..', '..', 'data', name), 'utf8'));
const result = analysePricing(normaliseInputs({ priceTests: read('price_test_results.csv'), sensitivity: read('price_sensitivity_survey.csv'), competitors: read('competitor_prices_by_channel.csv'), history: read('competitor_price_history.csv'), costs: read('cost_breakdown.csv'), channelEconomics: read('channel_economics.csv') }));
assert.deepEqual(result.facts.candidatePricesEur, [1.79, 2.19, 2.59]); assert.equal(result.priceTests.length, 3); assert.equal(result.priceTests[1].acceptancePct, 51.7); assert.equal(result.priceTests[1].channels.length, 3); assert.equal(result.priceTests[1].channels.find((row) => row.channel === 'Retail/Grocery').contributionPerUnitEur, 0.63); assert.equal(result.economics.cogsPerUnitEur, 0.62); assert.equal(result.priceSensitivity.respondentCount, 300); assert.equal(result.promotionDynamics.length, 4); assert.equal(result.tradeOff[0].channelContributions['DTC Online'], 0.77); assert.equal(require('./index').analysePricing, analysePricing);
const empty = analysePricing();
assert.equal(empty.priceSensitivity.acceptableRangeByCandidate[0].withinAcceptableRangePct, null);
assert.equal(empty.tradeOff[1].acceptancePct, null);
assert.deepEqual(empty.tradeOff[1].channelContributions, {});
assert.equal(require('./analysis').analyseCompetition([{ channel: 'New channel', format: 'Pack', price_eur: 2 }])[0].candidates[0].position, 'not available');
console.log('pricing analysis tests passed');
